/* RUMMIKUBE — Rummikub (open game) board solver (SHARED MODULE)
 *
 * Same text in two places (functions/rummySolver.js, index.html <script id="rummy-solver">);
 * `node sync-rummy-solver.js` regenerates the inline copy, `--check` verifies.
 *
 * Given the tiles on the table (ALL must stay on the table) and the bot's rack,
 * finds a complete re-arrangement of the table into valid sets/runs that places
 * the MAXIMUM number of rack tiles (ties: more points). This is the full
 * "manipulation" a strong human does — splitting runs, borrowing from sets,
 * rebuilding groups — not just appending to existing groups.
 *
 * Method: dynamic programming over values 1..13 (Den Hertog & Hulshof style).
 * State = for each colour the lengths (0,1,2,3+) of the two runs that may be
 * open (two copies of every tile), plus the number of jokers used. At each value
 * the tiles of that value are split between continuing/starting runs and forming
 * up to two sets of distinct colours. Jokers are "phantom" tiles at any position.
 * The value-1-high run (12-13-1) is not generated by the solver.
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.RummySolver = factory();
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
  var COLORS = ['#ef4444', '#3b82f6', '#f59e0b', '#0c1322'];
  var JOK = '☻';
  var isJ = function (t) { return !!t && t.val === JOK; };

  // per-slot transitions: slot length L → [{nl, uses}] (uses = takes a tile of this value)
  var SLOT = [
    [{ nl: 0, uses: 0 }, { nl: 1, uses: 1 }],          // L=0: stay empty / start a run
    [{ nl: 2, uses: 1 }],                               // L=1: must continue
    [{ nl: 3, uses: 1 }],                               // L=2: must continue
    [{ nl: 3, uses: 1 }, { nl: 0, uses: 0 }]            // L=3+: continue / close
  ];
  // per-colour transitions: state s=a*4+b, x tiles → list of {ns, acts:[actA, actB]} (act 1 = took a tile)
  var CTRANS = [];
  for (var s = 0; s < 16; s++) {
    CTRANS[s] = [[], [], []];
    var a = s >> 2, b = s & 3;
    for (var i = 0; i < SLOT[a].length; i++) for (var j = 0; j < SLOT[b].length; j++) {
      var oa = SLOT[a][i], ob = SLOT[b][j];
      var x = oa.uses + ob.uses;
      if (a === 0 && b === 0 && oa.uses === 0 && ob.uses === 1) continue; // start in slot A first (symmetry)
      CTRANS[s][x].push({ ns: oa.nl * 4 + ob.nl, acts: [oa.uses, ob.uses] });
    }
  }

  /* solve(boardTiles, rackTiles) → { groups: [tiles[]], placed: [rackTiles], score } | null
   * null = the table cannot be arranged at all (should not happen for a valid table). */
  function solve(boardTiles, rackTiles) {
    var M = [], R = [], v, c;
    for (v = 0; v <= 13; v++) { M[v] = [0, 0, 0, 0]; R[v] = [0, 0, 0, 0]; }
    var JB = 0, JR = 0;
    var pool = {}; // "v.c" -> {board:[], rack:[]}
    var pk = function (v2, c2) { return v2 + '.' + c2; };
    (boardTiles || []).forEach(function (t) { if (!t) return; if (isJ(t)) { JB++; return; } var ci = COLORS.indexOf(t.color), vv = Number(t.val); if (ci < 0 || !(vv >= 1 && vv <= 13)) return; M[vv][ci]++; (pool[pk(vv, ci)] = pool[pk(vv, ci)] || { board: [], rack: [] }).board.push(t); });
    (rackTiles || []).forEach(function (t) { if (!t) return; if (isJ(t)) { JR++; return; } var ci = COLORS.indexOf(t.color), vv = Number(t.val); if (ci < 0 || !(vv >= 1 && vv <= 13)) return; R[vv][ci]++; (pool[pk(vv, ci)] = pool[pk(vv, ci)] || { board: [], rack: [] }).rack.push(t); });
    var J = JB + JR;
    var jokersBoard = (boardTiles || []).filter(isJ), jokersRack = (rackTiles || []).filter(isJ);

    // boundary DP: key = runstates(4 colours, 4 bits each) | ju<<16  → {score, back}
    var layer = {};
    layer[0] = { score: 0, back: null };
    var layers = [layer];
    for (v = 1; v <= 13; v++) {
      var next = {};
      var keys = Object.keys(layer);
      for (var ki = 0; ki < keys.length; ki++) {
        var key = Number(keys[ki]);
        var st = layer[key];
        var S = [(key) & 15, (key >> 4) & 15, (key >> 8) & 15, (key >> 12) & 15];
        var ju0 = key >> 16;
        for (var t = 0; t <= 2; t++) {
          // sub-DP over colours: partial = {states, ju, sumY, score, choices}
          // n1 = colours giving ≥1 tile to sets, n2 = colours giving 2 (set #2 needs 3 of them)
          var partial = [{ S: S.slice(), ju: ju0, n1: 0, n2: 0, score: st.score, ch: [] }];
          for (c = 0; c < 4 && partial.length; c++) {
            var out = {};
            var avail = M[v][c] + R[v][c];
            for (var pi = 0; pi < partial.length; pi++) {
              var P = partial[pi];
              var jokLeft = J - P.ju;
              var maxN = Math.min(2, avail + jokLeft);
              for (var n = M[v][c]; n <= maxN; n++) {
                var ph = Math.max(0, n - avail);       // phantom (joker) tiles at this position
                var realUsed = n - ph;                 // ≥ M (mandatory board tiles)
                var rackUsed = realUsed - M[v][c];
                for (var y = 0; y <= Math.min(n, t); y++) {
                  var x = n - y;
                  var trs = CTRANS[P.S[c]][x];
                  for (var ti = 0; ti < trs.length; ti++) {
                    var S2 = P.S.slice(); S2[c] = trs[ti].ns;
                    var ju2 = P.ju + ph;
                    var n1b = P.n1 + (y >= 1 ? 1 : 0), n2b = P.n2 + (y >= 2 ? 1 : 0);
                    var sc = P.score + rackUsed * 100 + rackUsed * v;
                    var k2 = S2[0] | (S2[1] << 4) | (S2[2] << 8) | (S2[3] << 12) | (ju2 << 16) | (n1b << 20) | (n2b << 23);
                    if (!out[k2] || out[k2].score < sc) out[k2] = { S: S2, ju: ju2, n1: n1b, n2: n2b, score: sc, ch: P.ch.concat([{ c: c, n: n, x: x, y: y, ph: ph, acts: trs[ti].acts }]) };
                  }
                }
              }
            }
            partial = Object.keys(out).map(function (k) { return out[k]; });
          }
          for (var qi = 0; qi < partial.length; qi++) {
            var Q = partial[qi];
            // one set: ≥3 colours. Two sets: colours giving 2 tiles sit in both sets,
            // singles are split between them → both sets ≥3 iff n1 + n2 ≥ 6.
            if (t >= 1 && Q.n1 < 3) continue;
            if (t >= 2 && Q.n1 + Q.n2 < 6) continue;
            var bk = Q.S[0] | (Q.S[1] << 4) | (Q.S[2] << 8) | (Q.S[3] << 12) | (Q.ju << 16);
            if (!next[bk] || next[bk].score < Q.score) next[bk] = { score: Q.score, back: { key: key, t: t, ch: Q.ch } };
          }
        }
      }
      layer = next;
      layers.push(layer);
      if (!Object.keys(layer).length) return null;
    }
    // final: every open run is complete (slot 0 or 3+ — a run may end on 13), all
    // board jokers used; rack jokers count as placed tiles
    var bestKey = null, bestScore = -Infinity;
    Object.keys(layer).forEach(function (k) {
      var key = Number(k);
      for (var nb = 0; nb < 4; nb++) { var sl = (key >> (nb * 4)) & 15; if ((sl >> 2) === 1 || (sl >> 2) === 2 || (sl & 3) === 1 || (sl & 3) === 2) return; }
      var ju = key >> 16;
      if (ju < JB) return;
      var sc = layer[key].score + (ju - JB) * (100 + 30);
      if (sc > bestScore) { bestScore = sc; bestKey = key; }
    });
    if (bestKey == null) return null;

    // ── reconstruct ──
    var choices = []; // per value 1..13: {t, ch}
    var k = bestKey;
    for (v = 13; v >= 1; v--) { var b = layers[v][k].back; choices[v] = b; k = b.key; }
    var runs = [[[], []], [[], []], [[], []], [[], []]]; // per colour, per slot: current run tiles
    var groups = [], placed = [];
    var jb = jokersBoard.slice(), jr = jokersRack.slice();
    var takeJoker = function () { var t2 = jb.length ? jb.shift() : jr.shift(); if (t2 && jokersRack.indexOf(t2) >= 0) placed.push(t2); return t2; };
    var closeRun = function (c2, slot) { if (runs[c2][slot].length) { groups.push(runs[c2][slot]); runs[c2][slot] = []; } };
    for (v = 1; v <= 13; v++) {
      var ch = choices[v].ch, t2 = choices[v].t;
      var setPool = []; // tiles for sets this value, per colour
      for (var ci2 = 0; ci2 < ch.length; ci2++) {
        var d = ch[ci2], c3 = d.c;
        var pp = pool[pk(v, c3)] || { board: [], rack: [] };
        var tiles = [];
        for (var q = 0; q < d.n - d.ph; q++) {
          var tt = q < pp.board.length ? pp.board[q] : pp.rack[q - pp.board.length];
          tiles.push(tt);
          if (q >= pp.board.length) placed.push(tt);
        }
        for (var q2 = 0; q2 < d.ph; q2++) tiles.push(takeJoker());
        // runs first (the slots that continue/start take tiles), then sets
        var idx = 0;
        for (var sl = 0; sl < 2; sl++) {
          var prevLen = (sl === 0 ? ((choices[v].back ? 0 : 0)) : 0); // unused
          if (d.acts[sl] === 1) runs[c3][sl].push(tiles[idx++]);
          else if (runs[c3][sl].length) closeRun(c3, sl); // slot closed at this value
        }
        for (var q3 = idx; q3 < tiles.length; q3++) setPool.push({ c: c3, t: tiles[q3] });
      }
      // distribute set tiles into t2 sets: a colour giving two tiles is in both sets;
      // single tiles go to the smaller set so that both reach ≥3
      if (t2 > 0) {
        var sets = []; for (var si = 0; si < t2; si++) sets.push([]);
        var byC = {};
        setPool.forEach(function (e) { (byC[e.c] = byC[e.c] || []).push(e.t); });
        var singles = [];
        Object.keys(byC).forEach(function (cc) { var arr = byC[cc]; if (arr.length >= 2) { sets[0].push(arr[0]); sets[1 % t2].push(arr[1]); } else singles.push(arr[0]); });
        singles.forEach(function (tile) { var target = 0; for (var si2 = 1; si2 < t2; si2++) if (sets[si2].length < sets[target].length) target = si2; sets[target].push(tile); });
        sets.forEach(function (g) { if (g.length) groups.push(g); });
      }
    }
    for (c = 0; c < 4; c++) for (var sl2 = 0; sl2 < 2; sl2++) closeRun(c, sl2);
    return { groups: groups, placed: placed, score: bestScore };
  }

  return { solve: solve, COLORS: COLORS };
});
