const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function setup(){let starts=0,stops=0,contexts=0;const events={},saved={};
const param=()=>({value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}});
const w={document:{hidden:false,addEventListener(){}},localStorage:{getItem:k=>saved[k]??null,setItem:(k,v)=>saved[k]=v},addEventListener:(n,f)=>events[n]=f,AudioContext:class {constructor(){contexts++;this.state='running';this.currentTime=1;}createGain(){return {gain:param(),connect(){},disconnect(){}};}createOscillator(){return {frequency:param(),connect(){},disconnect(){},start(){starts++;},stop(){stops++;}};}}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../assets/js/game-audio.js'),'utf8'),{window:w});return {w,events,saved,stats:()=>({starts,stops,contexts})};}
test('audio starts only after a gesture and duplicate snapshots cannot stack a cue',()=>{const t=setup();t.w.GameAudio.play('turn');assert.equal(t.stats().contexts,0);t.events.pointerdown();t.w.GameAudio.play('turn');assert.equal(t.stats().starts,2);t.w.GameAudio.play('turn');assert.equal(t.stats().starts,2);});
test('mute stops scheduled sources, persists and hidden pages stay silent',()=>{const t=setup();t.events.pointerdown();t.w.GameAudio.play('win');const before=t.stats();t.w.GameAudio.setSettings({muted:true});assert.ok(t.stats().stops>before.stops);t.w.GameAudio.play('draw');assert.equal(t.stats().starts,before.starts);assert.equal(JSON.parse(t.saved.rummiAudio).muted,true);t.w.GameAudio.setSettings({muted:false,volume:10});assert.equal(t.w.GameAudio.settings().volume,1);t.w.document.hidden=true;t.w.GameAudio.play('tile');assert.equal(t.stats().starts,before.starts);});
test('unsupported audio and blocked storage cannot break gameplay',()=>{const w={document:{addEventListener(){}},localStorage:{getItem(){throw Error('blocked');}},addEventListener(){}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../assets/js/game-audio.js'),'utf8'),{window:w});assert.doesNotThrow(()=>{w.GameAudio.setSettings({volume:0});w.GameAudio.play('win');});});
test('one preference also controls legacy Tone cues',()=>{const t=setup();t.w.Tone={Destination:{mute:false,volume:{value:0}}};t.w.GameAudio.setSettings({volume:.2,muted:true});assert.equal(t.w.Tone.Destination.mute,true);t.w.GameAudio.setSettings({muted:false});assert.equal(t.w.Tone.Destination.mute,false);assert.ok(Math.abs(t.w.Tone.Destination.volume.value-20*Math.log10(.2))<1e-9);});
